# Generated by Django 3.2 on 2021-05-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.TimeField(),
        ),
    ]
